# Shared Network & Worker Settings
network_buffer_size=8192
so_buffer_size=0
network_send_timeout=0
network_thread_pool_size=0
vms_thread_pool_size=4
num_vms_workers=1
num_transaction_workers=4

# Logging & Checkpointing
logging=true
logging_type=default
checkpointing=false
checkpointing_truncate=true

# Scale Factor
num_ware=1

# Universal Memory Limits (Must be identical across all VMSs)
max_records.warehouse=1
max_records.district=10
max_records.customer=30000
max_records.item=100000
max_records.stock=100000
max_records.orders=1000000
max_records.new_orders=1000000
max_records.order_line=10000000
max_records.history=1000000
max_records.freshness=10